### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [graph90/Quantum-computing#1]
I recently came across your project Quantum-computing and I noticed that the repository github.com/graph90/Quantum-computing currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by graph90** [comment]
Hi @cbjuan,

Thank you for the suggestion! I've added an Apache 2.0 license to the repository as recommended. I appreciate you taking the time to point this out.

I noticed you work at IBM Quantum. I recently graduated from Ontario Tech University with a degree in Computer Science, where I took a quantum computing class that heavily focused on Qiskit. I’m eager to learn more about the field and what it’s like to work in quantum computing.

If you're open to it, I'd be happy to continue the conversation over email to learn more about your insights. You can reach me at nathaniel.armogan@ontariotechu.net.

Thanks again!

Best,
Nathaniel Armogan

**Comment by cbjuan** [comment]
Thank you!
